---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-ephemeral
spec:
  selector:
    matchLabels:
      app: nginx-ephemeral
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-ephemeral
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer

