---
- hosts: all
  gather_facts: no
  become: True

  tasks:
    - name: Setup Kubernetes master
      include_tasks: ../../tasks/kubernetes/kubernetes-master.yaml

  handlers:
    - name: docker status
      service: name=docker state=started
